### ISSUE TITLE
Not working with the standard browsers

### ISSUE THREAD

**Issue by PerttuSavolainen** [vastamaki/pagerduty-incidents#2]
Doesn't work with chromium based browsers. Please fix!

**Comment by vastamaki** [comment]
Please confirm that this issue is now fixed, test environment: https://pagerduty-incidents-git-add-standard-browser-support.vastamaki.vercel.app

**Comment by vastamaki** [comment]
I tested this using multiple devices, seems to be working now. Issue closed.
