### ISSUE TITLE
[BUG] Not all teams are included in my teams

### ISSUE THREAD

**Issue by nikolauska** [vastamaki/pagerduty-incidents#24]
**Describe the bug**
When filtering by my teams not all are used. It seems to use only the first teams and second one is not included. Manually selecting the second team shows the incidents for that team.

**To Reproduce**
1. Go to incidents list
2. See that the only incidents for some of the teams are included
3. Manually select team that is not shown is my teams
4. See the incidents for that team

**Expected behavior**
All of my users teams should be included in the incidents list without need to manually select team.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 79.0

**Comment by vastamaki** [comment]
@nikolauska Please try to reproduce the issue in the following environment: https://qa.pagerduty.customui.app

**Comment by nikolauska** [comment]
I've tested the QA environment and the issue has been fixed and I can see all my services

**Comment by vastamaki** [comment]
> I've tested the QA environment and the issue has been fixed and I can see all my services

Thanks for the confirmation. Fix for this is released in the latest patch v1.5.5
