### ISSUE TITLE
[BUG] Group by date doesn't respect sorting by last state change

### ISSUE THREAD

**Issue by nikolauska** [vastamaki/pagerduty-incidents#29]
**Describe the bug**
If I select sort by last state change which is different to create date it will still show in the date it was created on

**To Reproduce**
1. Go to incidents page
2. Select sort by last state change
3. Check the incident that has last state change on separate day to create date
4. See that it still grouped by create date

**Expected behavior**
Incident should switch to date the last state change was made and not stay on date it was created on.

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser Firefox
 - Version 79.0

**Comment by vastamaki** [comment]
I am currently working with larger refactoring, so this will be fixed after I am able to merge it.

**Comment by vastamaki** [comment]
This issue is fixed in the latest version.
